import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import crypto from 'node:crypto';
import worker,{hash} from '../worker/index.mjs';
const sketch=crypto.randomBytes(32).toString('base64url'),owner=crypto.randomBytes(32).toString('base64url');
const token=crypto.randomBytes(32).toString('base64url'),other=crypto.randomBytes(32).toString('base64url');
const id=crypto.randomUUID();
const db=new DatabaseSync(':memory:');db.exec(fs.readFileSync(new URL('../worker/schema.sql',import.meta.url),'utf8'));
const DB={prepare(sql){let args=[];const run={bind(...v){args=v;return run;},async first(){return db.prepare(sql).get(...args);},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}};}};return run;}};
const env={DB,SKETCH_KEY_HASH:await hash(sketch),ADMIN_KEY_HASH:await hash(owner),ALLOWED_ORIGIN:'https://imranncc.github.io'};
const data={name:'Synthetic reviewer',notebook:'test',orderGen:{Employment:['empl2','empl3']},orderOtt:{Employment:['empl3','empl2']},verdicts:{empl3:'strong'},threads:{empl3:[{text:'Test only',at:'2026-09-23'}]}};
const request=(method,path='/reviews/'+id,body,auth=token,key=sketch,origin=env.ALLOWED_ORIGIN)=>worker.fetch(new Request('https://api.example'+path,{method,headers:{Authorization:'Bearer '+auth,'X-Sketch-Key':key,'Content-Type':'application/json',Origin:origin},body:body?JSON.stringify(body):undefined}),env);
test('private storage, revisions, access control and validation',async()=>{
 assert.equal((await request('PUT',undefined,{data,revision:0},token,other)).status,403);
 assert.equal((await request('PUT',undefined,{data,revision:0})).status,200);
 let saved=await (await request('GET')).json();assert.deepEqual(saved.data,data);assert.equal(saved.revision,1);
 assert.equal((await request('GET',undefined,undefined,other)).status,401);
 assert.equal((await request('PUT',undefined,{data,revision:1},other)).status,401);
 assert.equal((await request('GET','/admin/reviews')).status,401);
 const all=await (await request('GET','/admin/reviews',undefined,owner)).json();assert.equal(all.reviews.length,1);assert.equal('token_hash' in all.reviews[0],false);
 assert.equal((await request('PUT',undefined,{data:{...data,notebook:'new'},revision:1})).status,200);
 assert.equal((await request('PUT',undefined,{data:{...data,notebook:'stale overwrite'},revision:1})).status,409);
 saved=await (await request('GET')).json();assert.equal(saved.data.notebook,'new');assert.equal(saved.revision,2);
 assert.equal((await request('GET',undefined,undefined,token,sketch,'https://unrelated.example')).status,403);
 assert.equal((await request('PUT',undefined,{data:{name:'invalid'},revision:2})).status,400);
 assert.equal((await request('PUT',undefined,{data:{...data,notebook:'x'.repeat(260000)},revision:2})).status,413);
 assert.equal((await request('GET','/reviews')).status,404);
});
